[Security]
EAP-Method=PEAP
EAP-Identity=anonymous@pollub.edu.pl
EAP-PEAP-CACert=embed:pollub_ca_cert
EAP-PEAP-Phase2-Method=MSCHAPV2
EAP-PEAP-Phase2-Identity=
EAP-PEAP-Phase2_Password=

[Settings]
Autoconnect=true

[@pem@pollub_ca_cert]
-----BEGIN CERTIFICATE-----
MIIFWDCCBECgAwIBAgIJANVy+CxpSDRHMA0GCSqGSIb3DQEBCwUAMIHNMQswCQYD
VQQGEwJQTDEXMBUGA1UECBMOd29qLiBMdWJlbHNraWUxDzANBgNVBAcTBkx1Ymxp
bjEeMBwGA1UEChMVUG9saXRlY2huaWthIEx1YmVsc2thMR0wGwYDVQQLExRJbnN0
eXR1dCBJbmZvcm1hdHlraTEqMCgGA1UEAxMhSUkgLSBXRWlJIC0gUG9saXRlY2hu
aWthIEx1YmVsc2thMSkwJwYJKoZIhvcNAQkBFhphZG1pbnNAcGx1dG9uLmNzLnBv
bGx1Yi5wbDAeFw0xOTA0MTgxMzE4MDNaFw0yOTA0MTUxMzE4MDNaMIHNMQswCQYD
VQQGEwJQTDEXMBUGA1UECBMOd29qLiBMdWJlbHNraWUxDzANBgNVBAcTBkx1Ymxp
bjEeMBwGA1UEChMVUG9saXRlY2huaWthIEx1YmVsc2thMR0wGwYDVQQLExRJbnN0
eXR1dCBJbmZvcm1hdHlraTEqMCgGA1UEAxMhSUkgLSBXRWlJIC0gUG9saXRlY2hu
aWthIEx1YmVsc2thMSkwJwYJKoZIhvcNAQkBFhphZG1pbnNAcGx1dG9uLmNzLnBv
bGx1Yi5wbDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMcqg/NgtxZ1
jeorFBb3uBP294J8tiNBM3Dg7Bktz8x1s+06cz1rg8h5LrP1GR/19zmZAKNRjkST
ZJ7+NQ+41QJoutWJneBnTj7nvWAU8Qd9S+9qZxVf25+lv4NJVQxkVfZWpmi9LCLc
q+X7xhzbPC6elL7HnJ54cbv7UCeKugLVUDfgYyp+fYiI09BIttKhniI5KfC/Gpuy
LrO+v1gRhbezhDvHemfQ62uMVL6RG1NpZ9QuZT1rrU0ApiKpF5qpNuIAS1wOOp9H
rssMlGkHh2FDVVTSmMV0HKvx6RnFTZhYGL+EepxI31lhYkav9vYVQ8rvls0cjE5x
h4wv+IIIWyECAwEAAaOCATcwggEzMB0GA1UdDgQWBBQct0Je2H3AInP/SiS8M/zV
CAo1vTCCAQIGA1UdIwSB+jCB94AUHLdCXth9wCJz/0okvDP81QgKNb2hgdOkgdAw
gc0xCzAJBgNVBAYTAlBMMRcwFQYDVQQIEw53b2ouIEx1YmVsc2tpZTEPMA0GA1UE
BxMGTHVibGluMR4wHAYDVQQKExVQb2xpdGVjaG5pa2EgTHViZWxza2ExHTAbBgNV
BAsTFEluc3R5dHV0IEluZm9ybWF0eWtpMSowKAYDVQQDEyFJSSAtIFdFaUkgLSBQ
b2xpdGVjaG5pa2EgTHViZWxza2ExKTAnBgkqhkiG9w0BCQEWGmFkbWluc0BwbHV0
b24uY3MucG9sbHViLnBsggkA1XL4LGlINEcwDAYDVR0TBAUwAwEB/zANBgkqhkiG
9w0BAQsFAAOCAQEABEd+YFGcUADuG6UD1fqaKJwlWGF91Rl6O6EL3bU3oBp/llS2
rHe4ZOx00UEnnrr3mcSclV1/Q2gPklMeTvjs/FkVKuZTnOwKl8FKmdHe0A9zsRwH
VdjP0QamWe4COISi3cxUxgjkn+BRsOwMaFsmWuTaz+qOqZe3cvTTb2Dwuiy8vcDG
DwYvYPhgN8WltEnyMxSbksqEjBSOV1YpJs8Ty/dvlbuYAJSULrRT2zXxxElSE/4D
FlDt0cvDmzcGAUBu+XUWy+vMqmvVEP1LJRJKqQILv8W7D2qSLHi1WDTbJZyTqJnx
06O8Se8eK4o8tWNKqPfiE1n8GR6fpK3WpMs+0g==
-----END CERTIFICATE-----
